spring:
  mail:
    host: smtp.163.com
    username: 17375603959@163.com
    password: LFQKZPKPIXEDDEDN
    nickname: 玲落尘肖
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: asdfghjkl123456
      expire: 7
      limit:
        base: 10
        upgrade: 300
        frequency: 30
  datasource:
    url: jdbc:mysql://localhost:3306/prediction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 9
#      username: root
#      password: root
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
