spring:
  mail:
    host: smtp.163.com
    username: XXXXXXX@163.com
    password: XXXXXXXXXXX
    nickname: yourNickName
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: asdfghjkl123456
      expire: 7
      limit:
        base: 10
        upgrade: 300
        frequency: 30
  datasource:
    url: jdbc:mysql://localhost:3306/prediction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 9
#      username: root
#      password: root
  influx:
    url: http://localhost:8086
    user: admin
    password: 123456789
    bucket: prediction
    org: xiaoxiao
    measurements:
      real: real
      predict: predict

  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    tushare:
      token: yourTushareToken
      url: http://api.tushare.pro
    data-treating:
      url: http://localhost
      port: 8888
  stock:
    favorite:
      max: 20
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
