spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prediction
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    jwt:
      key: asdfghjkl123456
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379
      database: 9
#      username: root
#      password: root
